{% set name = "nccl" %}
{% set version = "2.5.7" %}
{% set revision = "1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.{{ revision }}

source:
  url: https://github.com/NVIDIA/nccl/archive/v{{ version }}-{{ revision }}.tar.gz
  sha256: 781a6bb2278566be4abbdf22b2fa19afc7306cff4b312c82bd782979b368014e

build:
  number: 0
  skip: true  # [(not linux64) or (cuda_compiler_version == "None")]
  run_exports:
    # xref: https://github.com/NVIDIA/nccl/issues/218
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}
    - make

test:
  commands:
    - test -f "${PREFIX}/include/nccl.h"
    - test -f "${PREFIX}/lib/libnccl.so"
    - test -f "${PREFIX}/lib/libnccl_static.a"

about:
  home: https://developer.nvidia.com/nccl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Optimized primitives for collective multi-GPU communication

  description: |
    The NVIDIA Collective Communications Library (NCCL) implements multi-GPU
    and multi-node collective communication primitives that are performance
    optimized for NVIDIA GPUs. NCCL provides routines such as all-gather,
    all-reduce, broadcast, reduce, reduce-scatter, that are optimized to
    achieve high bandwidth over PCIe and NVLink high-speed interconnect.

  doc_url: https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/index.html
  dev_url: https://github.com/NVIDIA/nccl

extra:
  recipe-maintainers:
    - jakirkham
