azure:
  free_disk_space: true
bot:
  automerge: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_build:
  error_overlinking: true
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
