conda_forge_output_validation: true
os_version:
  linux_64: cos6
github:
  branch_name: main
  tooling_branch_name: main
bot:
  automerge: true
conda_build:
  pkg_format: '2'
test: native_and_emulated
